@extends('layouts.app')
@section('title','Submit Land for Joint Venture | InternEstate')
@section('content')
<section class="land-wizard-page"><div class="land-wizard-shell">
<header class="land-wizard-intro"><span>JOINT VENTURE DEVELOPMENT</span><h1>Turn your land into a lasting asset.</h1><p>Submit your property securely. Our legal and development teams will evaluate it and keep you informed at every stage.</p></header>
@if(session('submission_success'))<div class="land-success"><span>✓</span><div><h2>Submission received</h2><p>Your unique tracking code is</p><strong>{{ session('submission_success') }}</strong><small>Save this code. Our legal team will contact you after initial review.</small></div></div>@else
<div class="wizard-steps"><button class="active" data-wizard-step="1"><b>1</b><span>Land Details</span></button><i></i><button data-wizard-step="2"><b>2</b><span>Ownership</span></button><i></i><button data-wizard-step="3"><b>3</b><span>Confirm</span></button></div>
<form method="POST" action="{{ route('land.submit.store') }}" enctype="multipart/form-data" id="landWizard" class="land-wizard-card">@csrf
<section class="wizard-panel active" data-wizard-panel="1"><div class="wizard-heading"><span>01</span><div><h2>Tell us about the land</h2><p>Location, access and plot measurements.</p></div></div><div class="land-form-grid"><label>Phone number<input name="phone" value="{{ old('phone') }}" pattern="01[3-9][0-9]{8}" placeholder="01XXXXXXXXX" required></label><label>Division<select name="division" required><option value="">Select division</option>@foreach($divisions as $division)<option @selected(old('division')===$division)>{{ $division }}</option>@endforeach</select></label><label>District<input name="district" value="{{ old('district') }}" required></label><label>Land size (Katha)<input type="number" step=".01" min=".01" name="katha" value="{{ old('katha') }}" required></label><label class="wide">Location address<textarea name="location" required>{{ old('location') }}</textarea></label><label>Road width (feet)<input type="number" min="1" name="road_width" value="{{ old('road_width') }}" required></label><label>Nearby landmark<input name="landmark" value="{{ old('landmark') }}"></label><label class="wide">Short description<textarea name="description">{{ old('description') }}</textarea></label></div></section>
<section class="wizard-panel" data-wizard-panel="2"><div class="wizard-heading"><span>02</span><div><h2>Legal ownership</h2><p>Details must match the submitted NID and title deed.</p></div></div><div class="land-form-grid"><label>Owner full name<input name="owner_name" value="{{ old('owner_name') }}" required></label><label>NID number<input name="nid_number" value="{{ old('nid_number') }}" minlength="10" maxlength="20" required></label><label class="file-field">Title deed / document copy<input type="file" name="deed_path" accept=".pdf,.jpg,.jpeg,.png" required><small>PDF, JPG or PNG · maximum 5 MB</small></label><label class="file-field">Owner NID copy<input type="file" name="nid_path" accept=".pdf,.jpg,.jpeg,.png" required><small>PDF, JPG or PNG · maximum 5 MB</small></label></div></section>
<section class="wizard-panel" data-wizard-panel="3"><div class="wizard-heading"><span>03</span><div><h2>Review & confirmation</h2><p>Confirm the information before secure submission.</p></div></div><div id="landReview" class="land-review"></div><label class="land-consent"><input type="checkbox" required> I confirm that the information and uploaded ownership documents are accurate.</label></section>
@if($errors->any())<div class="land-errors">{{ $errors->first() }}</div>@endif
<footer class="wizard-actions"><button type="button" id="wizardBack" class="wizard-back" hidden>← Back</button><button type="button" id="wizardNext" class="wizard-next">Continue →</button><button type="submit" id="wizardSubmit" class="wizard-next" hidden>Submit securely</button></footer>
</form>@endif
<div class="land-assurance"><div><b>Private & encrypted</b><span>Documents are stored securely</span></div><div><b>Legal review</b><span>Property counsel verifies ownership</span></div><div><b>Transparent tracking</b><span>Follow every JV stage</span></div></div>
</div></section>
@endsection
