@extends('layouts.portal')
@section('title','Admin Command Center | InternEstate') @section('page-heading','Admin Command Center')
@section('content')
<div class="erp-hero"><div><span class="erp-kicker">LIVE OPERATIONS</span><h2>Build with clarity. Lead with data.</h2><p>Portfolio, finance, workforce and legal intelligence in one operational view.</p></div><a class="erp-button" href="{{ route('admin.erp') }}">Open ERP Hub →</a></div>
<section class="erp-kpis"><article><span>Active Projects</span><b>{{ $stats['active_projects'] }}</b><small>Live construction sites</small></article><article><span>Budget Spent</span><b>৳{{ number_format($stats['budget_spent']/1000000,1) }}M</b><small>All recorded expenses</small></article><article><span>Active Workers</span><b>{{ $stats['active_workers'] }}</b><small>Checked in today</small></article><article><span>Pending Legal</span><b>{{ $stats['pending_legal'] }}</b><small>Awaiting vetting</small></article></section>
<div class="erp-two"><section class="erp-panel"><div class="erp-panel-head"><div><h3>Portfolio Control</h3><p>AI delay risk and budget health</p></div><a href="{{ route('erp.projects') }}">Manage projects</a></div><div class="erp-table-wrap"><table class="erp-table"><thead><tr><th>Project</th><th>Status</th><th>Progress</th><th>Spent / Budget</th><th>AI Risk</th></tr></thead><tbody>@forelse($risks as $row)<tr><td><b>{{ $row['project']->title }}</b><small>{{ $row['project']->location }}</small></td><td><span class="erp-pill">{{ $row['project']->status }}</span></td><td>{{ $row['project']->progress_percentage }}%</td><td>৳{{ number_format($row['spent']) }} / ৳{{ number_format($row['project']->total_budget) }}</td><td><span class="erp-risk {{ strtolower($row['risk']) }}">{{ $row['risk'] }}</span></td></tr>@empty<tr><td colspan="5" class="erp-empty">No projects yet. Open ERP Hub to create the first project.</td></tr>@endforelse</tbody></table></div></section>
<aside class="erp-panel"><div class="erp-panel-head"><div><h3>System Health</h3><p>Operational services</p></div></div><div class="health-row"><span>Database</span><b>Operational</b></div><div class="health-row"><span>Authentication</span><b>Protected</b></div><div class="health-row"><span>ERP Modules</span><b>10 Online</b></div><div class="health-row"><span>Audit Capture</span><b>Active</b></div><a class="erp-secondary" href="{{ route('admin.audit') }}">View full audit trail</a></aside></div>
<section class="erp-panel"><div class="erp-panel-head"><div><h3>Land Submission Queue</h3><p>Legal verification workflow</p></div><a href="{{ route('admin.lawyers') }}">Open legal desk</a></div><div class="erp-table-wrap"><table class="erp-table"><thead><tr><th>Property</th><th>Division</th><th>Area</th><th>Asking Price</th><th>Status</th></tr></thead><tbody>@forelse($submissions as $item)<tr><td>{{ $item->title }}</td><td>{{ $item->division }}</td><td>{{ number_format($item->area_sqft) }} sqft</td><td>৳{{ number_format($item->asking_price) }}</td><td><span class="erp-pill">{{ $item->status }}</span></td></tr>@empty<tr><td colspan="5" class="erp-empty">No pending land submissions.</td></tr>@endforelse</tbody></table></div></section>
<section class="erp-panel erp-chart-panel"><div class="erp-panel-head"><div><h3>Budget Baseline vs Actual</h3><p>Portfolio overrun monitoring</p></div></div><canvas id="budgetChart"></canvas></section>
@endsection
@push('head')<script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.7/dist/chart.umd.min.js" defer></script>@endpush
@push('scripts')<script>window.addEventListener('load',()=>{const el=document.getElementById('budgetChart');if(!el||typeof Chart==='undefined')return;new Chart(el,{type:'bar',data:{labels:@json($risks->pluck('project.title')),datasets:[{label:'Budget',data:@json($risks->pluck('project.total_budget')->map(fn($v)=>(float)$v)),backgroundColor:'rgba(99,102,241,.55)'},{label:'Actual',data:@json($risks->pluck('spent')),backgroundColor:'rgba(16,185,129,.75)'}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{labels:{color:'#94a3b8'}}},scales:{x:{ticks:{color:'#94a3b8'},grid:{color:'rgba(148,163,184,.08)'}},y:{ticks:{color:'#94a3b8'},grid:{color:'rgba(148,163,184,.08)'}}}}});});</script>@endpush
