@extends('layouts.portal')
@section('page-heading','Legal Desk')
@section('content')
<div class="erp-hero compact"><div><span class="erp-kicker">LAND DUE DILIGENCE</span><h2>Lawyers & JV Submission Review</h2><p>Assign counsel, verify ownership, define the JV split and activate development.</p></div></div>
<section class="erp-panel"><div class="erp-panel-head"><h3>Land Submission Queue</h3></div><div class="erp-table-wrap"><table class="erp-table"><thead><tr><th>Tracking / Property</th><th>Stage</th><th>Lawyer</th><th>JV Decision</th></tr></thead><tbody>
@forelse($submissions as $s)<tr><td><b>{{ $s->code ?? $s->title }}</b><small>{{ $s->landowner_name }} · {{ $s->location }}</small></td><td><span class="erp-pill">{{ $s->stage ?? $s->status }}</span></td><td><form method="POST" action="{{ route('admin.submissions.assign',$s) }}" class="erp-row-form">@csrf<select name="lawyer_id" required><option value="">Assign…</option>@foreach($lawyers as $l)<option value="{{ $l->id }}" @selected($s->assigned_lawyer_id===$l->id)>{{ $l->name }}</option>@endforeach</select><button>Assign</button></form></td><td><div class="jv-admin-actions"><form method="POST" action="{{ route('admin.submissions.approve',$s) }}" class="erp-row-form">@csrf<input type="number" name="landowner_share_pct" value="40" min="10" max="90" title="Landowner share %"><input name="allocated_flats" placeholder="A4, B6" title="Comma-separated flat codes"><button>Draft JV & Approve</button></form><form method="POST" action="{{ route('admin.submissions.reject',$s) }}" class="erp-row-form">@csrf<input name="rejection_reason" placeholder="Rejection reason"><button class="danger">Reject</button></form></div></td></tr>
@empty<tr><td colspan="4" class="erp-empty">No submissions.</td></tr>@endforelse
</tbody></table></div></section>
<section class="erp-panel"><div class="erp-panel-head"><h3>Lawyer Directory</h3></div><div class="erp-module-grid">@forelse($lawyers as $l)<a href="#"><span>PROPERTY COUNSEL</span><h3>{{ $l->name }}</h3><p>{{ $l->specialization }} · {{ $l->phone }}</p><b>{{ $l->active_cases_count }} active cases</b></a>@empty<p class="erp-empty">No lawyers added.</p>@endforelse</div></section>
@endsection
