@extends('layouts.portal') @section('page-heading',ucwords(str_replace('-',' ',$module)))
@section('content')
<div class="erp-hero compact"><div><span class="erp-kicker">CONSTRUCTION ERP</span><h2>{{ ucwords(str_replace('-',' ',$module)) }}</h2><p>Live operational records, actions and exception monitoring.</p></div><button class="erp-button" data-modal-open="recordModal">+ Add record</button></div>
@if($module==='inventory')<form method="POST" action="{{ route('erp.inventory.reorder') }}" class="erp-inline-action">@csrf<button class="erp-secondary">⚡ Run AI Auto-Reorder</button></form>@endif
<section class="erp-panel"><div class="erp-panel-head"><div><h3>Recent Records</h3><p>{{ $records->count() }} latest entries</p></div></div><div class="erp-table-wrap"><table class="erp-table"><thead><tr>@if($records->isNotEmpty()) @foreach(array_slice(array_keys((array)$records->first()),0,7) as $column)<th>{{ str_replace('_',' ',$column) }}</th>@endforeach @endif</tr></thead><tbody>@forelse($records as $record)<tr>@foreach(array_slice((array)$record,0,7) as $value)<td>{{ is_string($value)?\Illuminate\Support\Str::limit($value,35):$value }}</td>@endforeach</tr>@empty<tr><td class="erp-empty">No records yet. Use “Add record” to begin.</td></tr>@endforelse</tbody></table></div></section>
<dialog class="erp-modal" id="recordModal"><form method="POST" action="{{ $module==='projects'?route('erp.projects.store'):($module==='tasks'?route('erp.tasks.store'):($module==='inventory'?route('erp.inventory.materials'):($module==='finance'?route('erp.finance.expenses'):route('erp.'.$module.'.store')))) }}">@csrf<div class="erp-modal-head"><div><span class="erp-kicker">QUICK ENTRY</span><h3>New {{ ucfirst($module) }} record</h3></div><button type="button" data-modal-close>×</button></div><div class="erp-form">
@if($module==='projects')<label>Project title<input name="title" required></label><label>Location<input name="location" required></label><label>Division<input name="division"></label><label>Total budget<input type="number" name="total_budget" required min="0"></label><label>Land area (sqft)<input type="number" name="land_area" min="0"></label><label>Status<select name="status"><option>planned</option><option>active</option><option>delayed</option><option>completed</option></select></label><label>Start date<input type="date" name="start_date"></label><label>End date<input type="date" name="end_date"></label>
@elseif($module==='tasks')<label>Project<select name="project_id" required>@foreach($projects as $p)<option value="{{ $p->id }}">{{ $p->title }}</option>@endforeach</select></label><label>Task title<input name="title" required></label><label>Assigned to<select name="assigned_to"><option value="">Unassigned</option>@foreach($users as $u)<option value="{{ $u->id }}">{{ $u->name }}</option>@endforeach</select></label><label>Priority<select name="priority"><option>low</option><option selected>medium</option><option>high</option><option>critical</option></select></label><label>Progress<input type="number" name="progress" value="0" min="0" max="100"></label><label>Status<input name="status" value="pending"></label>
@elseif($module==='inventory')<label>Name<input name="name" required></label><label>Category<input name="category" required></label><label>Current stock<input type="number" step=".01" name="current_stock" required></label><label>Unit<input name="unit" placeholder="bags, ton, pcs" required></label><label>Reorder level<input type="number" step=".01" name="reorder_level" required></label><label>Unit price<input type="number" step=".01" name="unit_price" required></label>
@elseif($module==='finance')<label>Project<select name="project_id" required>@foreach($projects as $p)<option value="{{ $p->id }}">{{ $p->title }}</option>@endforeach</select></label><label>Category<select name="category">@foreach(['Materials','Labor','Equipment','Legal','Overhead'] as $v)<option>{{ $v }}</option>@endforeach</select></label><label>Amount<input type="number" step=".01" name="amount" required></label><label>Payment method<input name="payment_method" value="Bank Transfer" required></label><label>Date<input type="date" name="date" value="{{ now()->toDateString() }}" required></label><label>Description<textarea name="description"></textarea></label>
@elseif($module==='equipment')<label>Name<input name="name" required></label><label>Serial number<input name="serial_number" required></label><label>Category<input name="category" required></label><label>Status<select name="operational_status"><option>Active</option><option>Under Maintenance</option><option>Idle</option></select></label><label>Hours logged<input type="number" name="total_hours_logged" value="0"></label><label>Next maintenance<input type="date" name="next_maintenance_due"></label>
@elseif($module==='procurement')<label>Project<select name="project_id"><option value="">General stock</option>@foreach($projects as $p)<option value="{{ $p->id }}">{{ $p->title }}</option>@endforeach</select></label><label>Material<select name="material_id" required>@foreach($materials as $m)<option value="{{ $m->id }}">{{ $m->name }}</option>@endforeach</select></label><label>Quantity<input type="number" step=".01" name="quantity" required></label><label>Status<input name="status" value="pending" required></label>
@elseif($module==='workforce')<label>Worker name<input name="worker_name" required></label><label>Project<select name="project_id" required>@foreach($projects as $p)<option value="{{ $p->id }}">{{ $p->title }}</option>@endforeach</select></label><label>QR scan hash<input name="qr_code_hash" value="{{ \Illuminate\Support\Str::uuid() }}" required></label><label>Check in<input type="datetime-local" name="check_in" value="{{ now()->format('Y-m-d\TH:i') }}" required></label><label>Status<input name="status" value="present"></label>
@elseif($module==='site-progress')<label>Project<select name="project_id" required>@foreach($projects as $p)<option value="{{ $p->id }}">{{ $p->title }}</option>@endforeach</select></label><label>Report date<input type="date" name="report_date" value="{{ now()->toDateString() }}" required></label><label>Weather<input name="weather_condition" value="Clear"></label><label>Labor count<input type="number" name="labor_count" required></label><label class="wide">Work summary<textarea name="work_summary" required></textarea></label>
@elseif($module==='inspections')<label>Project<select name="project_id" required>@foreach($projects as $p)<option value="{{ $p->id }}">{{ $p->title }}</option>@endforeach</select></label><label>Inspector<input name="inspector_name" required></label><label>Inspection type<input name="inspection_type" required></label><label>Result<select name="result"><option>Pass</option><option>Fail</option><option>Needs Action</option></select></label><label>Inspection date<input type="date" name="inspection_date" value="{{ now()->toDateString() }}" required></label><label>Remarks<textarea name="remarks"></textarea></label>
@elseif($module==='documents')<label>Project<select name="project_id" required>@foreach($projects as $p)<option value="{{ $p->id }}">{{ $p->title }}</option>@endforeach</select></label><label>Title<input name="title" required></label><label>Category<select name="category"><option>Drawing</option><option>Architectural</option><option>Structural</option><option>Legal</option></select></label><label>File path<input name="file_path" required></label><label>Version<input name="version" value="1.0"></label><label>Approval status<input name="approval_status" value="pending"></label>@endif
</div><div class="erp-modal-actions"><button type="button" data-modal-close>Cancel</button><button class="erp-button">Save record</button></div></form></dialog>
@if($module==='projects')
<section class="erp-panel"><div class="erp-panel-head"><div><h3>Project status controls</h3><p>Updates are reflected in both Landowner and Investor portals.</p></div></div>@foreach($records as $record)<form method="POST" action="{{ route('erp.projects.update', $record->id) }}" class="erp-row-form">@csrf @method('PATCH')<b>{{ $record->title }}</b><select name="status">@foreach(['planned','active','delayed','completed'] as $status)<option value="{{ $status }}" @selected($record->status === $status)>{{ ucfirst($status) }}</option>@endforeach</select><input type="number" name="progress_percentage" min="0" max="100" value="{{ $record->progress_percentage }}"><input type="date" name="end_date" value="{{ $record->end_date }}"><button type="submit">Update portal status</button></form>@endforeach</section>
@endif
@if($module==='tasks')
@foreach($records as $record)<dialog class="erp-modal" id="editTasksModal-{{ $record->id }}"><form method="POST" action="{{ route('erp.tasks.update',$record->id) }}">@csrf @method('PUT')<div class="erp-modal-head"><div><span class="erp-kicker">ADMIN CONTROL</span><h3>Edit task</h3></div><button type="button" data-modal-close>Close</button></div><div class="erp-form"><label>Project<select name="project_id">@foreach($projects as $p)<option value="{{ $p->id }}" @selected($record->project_id==$p->id)>{{ $p->title }}</option>@endforeach</select></label><label>Task title<input name="title" value="{{ $record->title }}" required></label><label>Assigned to<select name="assigned_to"><option value="">Unassigned</option>@foreach($users as $u)<option value="{{ $u->id }}" @selected($record->assigned_to==$u->id)>{{ $u->name }}</option>@endforeach</select></label><label>Priority<select name="priority">@foreach(['low','medium','high','critical'] as $priority)<option value="{{ $priority }}" @selected($record->priority===$priority)>{{ $priority }}</option>@endforeach</select></label><label>Start date<input type="date" name="start_date" value="{{ $record->start_date }}"></label><label>End date<input type="date" name="end_date" value="{{ $record->end_date }}"></label><label>Progress<input type="number" name="progress" min="0" max="100" value="{{ $record->progress }}"></label><label>Status<input name="status" value="{{ $record->status }}" required></label></div><div class="erp-modal-actions"><button type="button" data-modal-close>Cancel</button><button class="erp-button">Save changes</button></div></form></dialog>@endforeach
<section class="erp-panel"><div class="erp-panel-head"><div><h3>Admin controls</h3><p>Edit or delete tasks.</p></div></div>@foreach($records as $record)<div class="health-row"><b>{{ $record->title }}</b><div class="erp-actions"><button type="button" data-modal-open="editTasksModal-{{ $record->id }}">Edit</button><form method="POST" action="{{ route('erp.tasks.destroy',$record->id) }}" onsubmit="return confirm('Delete this task?')">@csrf @method('DELETE')<button class="danger">Delete</button></form></div></div>@endforeach</section>
@elseif($module==='inventory')
@foreach($records as $record)<dialog class="erp-modal" id="editInventoryModal-{{ $record->id }}"><form method="POST" action="{{ route('erp.inventory.materials.update',$record->id) }}">@csrf @method('PUT')<div class="erp-modal-head"><div><span class="erp-kicker">ADMIN CONTROL</span><h3>Edit material</h3></div><button type="button" data-modal-close>Close</button></div><div class="erp-form"><label>Name<input name="name" value="{{ $record->name }}" required></label><label>Category<input name="category" value="{{ $record->category }}" required></label><label>Current stock<input type="number" step=".01" name="current_stock" value="{{ $record->current_stock }}" required></label><label>Unit<input name="unit" value="{{ $record->unit }}" required></label><label>Reorder level<input type="number" step=".01" name="reorder_level" value="{{ $record->reorder_level }}" required></label><label>Unit price<input type="number" step=".01" name="unit_price" value="{{ $record->unit_price }}" required></label></div><div class="erp-modal-actions"><button type="button" data-modal-close>Cancel</button><button class="erp-button">Save changes</button></div></form></dialog>@endforeach
<section class="erp-panel"><div class="erp-panel-head"><div><h3>Admin controls</h3><p>Edit or delete materials.</p></div></div>@foreach($records as $record)<div class="health-row"><b>{{ $record->name }}</b><div class="erp-actions"><button type="button" data-modal-open="editInventoryModal-{{ $record->id }}">Edit</button><form method="POST" action="{{ route('erp.inventory.materials.destroy',$record->id) }}" onsubmit="return confirm('Delete this material?')">@csrf @method('DELETE')<button class="danger">Delete</button></form></div></div>@endforeach</section>
@endif
@if($module==='tasks')
<script>
document.addEventListener('DOMContentLoaded', () => {
    const panels = document.querySelectorAll('.erp-panel');
    const controlsPanel = panels[panels.length - 1];
    const actions = controlsPanel?.querySelectorAll('.erp-actions') ?? [];
    const rows = document.querySelectorAll('.erp-table tbody tr');
    if (!actions.length || actions.length !== rows.length) return;

    const header = document.querySelector('.erp-table thead tr');
    const actionHeader = document.createElement('th');
    actionHeader.textContent = 'Actions';
    header?.appendChild(actionHeader);

    actions.forEach((action, index) => {
        const cell = document.createElement('td');
        cell.appendChild(action);
        rows[index].appendChild(cell);
    });
    controlsPanel.remove();
});
</script>
@endif
@endsection
