<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>@yield('title','Command Center | InternEstate')</title>@vite(['resources/css/app.css','resources/js/app.js'])@stack('head')</head>
<body class="erp-dark admin-portal"><div class="erp-shell">
<aside class="erp-sidebar" id="portalSidebar"><a href="{{ route('admin.dashboard') }}" class="erp-brand"><span>IE</span><div>InternEstate<small>COMMAND CENTER</small></div></a>
<nav><p>CONTROL</p><a class="{{ request()->routeIs('admin.dashboard')?'active':'' }}" href="{{ route('admin.dashboard') }}">◫ Overview</a><a class="{{ request()->routeIs('admin.erp')?'active':'' }}" href="{{ route('admin.erp') }}">◆ ERP Hub</a><a href="{{ route('erp.projects') }}">▦ Projects</a><a href="{{ route('erp.tasks') }}">✓ Tasks</a><a href="{{ route('erp.inventory') }}">▤ Inventory</a><a href="{{ route('erp.procurement') }}">⌁ Procurement</a><a href="{{ route('erp.workforce') }}">◎ Workforce</a><a href="{{ route('erp.finance') }}">৳ Finance</a>
<p>GOVERNANCE & INVESTORS</p><a class="{{ request()->routeIs('admin.investors')?'active':'' }}" href="{{ route('admin.investors') }}">🤝 Investor Operations</a><a class="{{ request()->routeIs('admin.investor-documents')?'active':'' }}" href="{{ route('admin.investor-documents') }}">📁 Investor Documents</a><a href="{{ route('admin.lawyers') }}">⚖ Legal Desk</a><a href="{{ route('admin.audit') }}">◷ Audit Trail</a></nav>
<div class="erp-sidebar-foot"><a href="{{ route('landing') }}">← Public website</a><form method="POST" action="{{ route('logout') }}">@csrf<button>Sign out</button></form></div></aside>
<section class="erp-main"><header class="erp-topbar"><button id="sidebarToggle" class="erp-menu">☰</button><div><small>{{ now()->timezone('Asia/Dhaka')->format('l, d F Y · h:i A') }}</small><h1>@yield('page-heading','Command Center')</h1></div><div class="erp-user"><span>{{ strtoupper(substr(auth()->user()->name,0,1)) }}</span><div><b>{{ auth()->user()->name }}</b><small>{{ ucfirst(auth()->user()->role) }}</small></div></div></header>
<main class="erp-content">@if(session('success'))<div class="erp-notice">✓ {{ session('success') }}</div>@endif @if($errors->any())<div class="erp-error">{{ $errors->first() }}</div>@endif @yield('content')</main></section>
</div>@stack('scripts')</body></html>
